### ISSUE TITLE
Blueboxes stopped working (with background expansion enabled)

### ISSUE THREAD

**Issue by jsmaniac** [racket/drracket#118]
Steps to reproduce:

1. Download the snapshot `20170517-8bc9cef7a9` or a later one from https://plt.eecs.northwestern.edu/snapshots/, version "64-bit x86_64 built on Ubuntu Precise Pangolin".
2. Install it in a fresh Ubuntu 14.04.4 VirtualBox machine
3. Run DrRacket
4. Select "The Racket language" in the Ctrl+L language selection window
5. Enable background expansion
6. Type this program (for example):
```
#lang racket
(+)
```
6. When the cursor is on `+`, the blue boxes do not appear.

The blue boxes appear correctly when installing the latest stable version ([6.9](https://mirror.racket-lang.org/installers/6.9/racket-6.9-x86_64-linux.sh)), but do not appear at all starting from the snapshot version `20170517-8bc9cef7a9`. The issue was therefore introduced between `20170510-e6793c4598` and `20170517-8bc9cef7a9`.

Recent versions of DrRacket disable background expansion by default on single-CPU machines (see #117). This is not the source of the problem, however, after enabling background expansion and making a change to the file (to force the background expansion to run), the blue boxes still do not appear on recent builds, even on a real (non-VM) multicore machine.

**Comment by hashimmm** [comment]
This problem exists for me in the stable 6.10 release as well.

**Comment by rfindler** [comment]
There were two bugs in play here. First, the specification of the format of the blueboxes file was wrong (as fixed in the commit mentioned above). But that check was in place way before the error started happening. The reason they stopped working when they did was that a bug fix (https://github.com/racket/racket/commit/65beb4de4cd) caused the (incorrect) predicate to go from (incorrectly) accepting the correct format to rejecting it.

Sorry for taking so long to look into this one.

**Comment by jsmaniac** [comment]
Did this fix make it into 6.10? I have `6.10.0.3` installed here and I still do not see the blue boxes.

**Comment by jsmaniac** [comment]
My bad, I hadn't realised that I had a local copy of `gui` and `scribble`, which had not been updated by `raco pkg update -a`. Everything works fine on 6.10
