### ISSUE TITLE
"Uncomment" menu item fails on Linux/Wayland/GTK3

### ISSUE THREAD

**Issue by samth** [racket/drracket#587]
Selecting text and using the "Racket|Uncomment" menu item does nothing on Linux with Wayland and GTK3. With `PLT_GTK2=1` set, it works correctly.

**Comment by shhyou** [comment]
Fixed by merging racket/gui#316 or it is a different issue?

**Comment by rfindler** [comment]
Oh, that would be nice if that did fix it!

**Comment by jbclements** [comment]
Per the discourse at https://racket.discourse.group/t/uncommenting-does-not-work-on-any-linux-distro-with-gnome-3/1299/12 it appears that this bug is not fixed?

**Comment by samth** [comment]
I can confirm that this bug is still there, but only on Wayland.
